# SharePoint 設定
sharepoint:
  site_host: "ncnj.sharepoint.com"
  site_path: "/sites/staff_sharedfolders"
  graph_base: "https://graph.microsoft.com/v1.0"

# ダウンロード対象ファイル
# ファイルはいくつ指定してもよい。sava_nameも自由に設定可能
# remote_path: SharePoint上のファイルパス（年度変更時にここを書き換える）
# save_name:   ローカル保存名
files:
  - remote_path: "140.スケジュール・時間割/2026(R8)年度 時間割/【2026・04～09月 前期】全学年時間割.xlsx"
    save_name: "data/schedule_spring_2026.xlsx"
  - remote_path: "140.スケジュール・時間割/2026(R8)年度 時間割/【2026・10～03月 後期】全学年時間割.xlsx"
    save_name: "data/schedule_fall_2026.xlsx"

sheet_pattern: "(\\d{4})年度\\((.*?)(前期|後期)\\)"

# 出力先
output:
  schedule_json: "docs/schedule.json"
  info_json: "docs/info.json"

# 助産統合の対象
josan:
  source_grade: "4年"
  target_grade: "助産"

# 表示期間の切り替え
display_period:
  start_date: "2026-04-01"
  end_date: "2027-03-31"
